### ISSUE TITLE
new "Shorts" tab broken by this extension

### ISSUE THREAD

**Issue by Rathmox** [doma-itachi/Youtube-shorts-block#14]
I tried to click the "Shorts" tab on a YouTube channel and I've been taken to this page: `https://www.youtube.com/watch?v=undefined`

I don't think much can be done for this but I wanted to warn about it

**Comment by doma-itachi** [comment]
I'm sorry for the late reply.
I can't guarantee a fix, but if you don't mind, could you tell me what browser you are using, how often it happens, and the URL before the redirect after the button is pressed?

**Comment by Jarombean** [comment]
I'm running on Mozilla Firefox and am having this issue as well
With the extension disabled, the shorts tab directs to
https://www.youtube.com/c/ChannelName/shorts. However with the extension It instantly redirects to https://www.youtube.com/c/ChannelName and then to https://www.youtube.com/watch?v=undefined

I'm not a JS developer, but
Perhaps it's picking up the /shorts in the URL and Identifying it with a Shorts URL, But since there's no video ID following in the URL, Maybe it's redirecting to https://www.youtube.com/watch?v=undefined

**Comment by Rathmox** [comment]
maybe the extension shouldn't search for `/shorts` but for `/shorts/`

**Comment by ajddavid452** [comment]
> I'm running on Mozilla Firefox and am having this issue as well With the extension disabled, the shorts tab directs to https://www.youtube.com/c/ChannelName/shorts. However with the extension It instantly redirects to https://www.youtube.com/c/ChannelName and then to https://www.youtube.com/watch?v=undefined
> 
> I'm not a JS developer, but Perhaps it's picking up the /shorts in the URL and Identifying it with a Shorts URL, But since there's no video ID following in the URL, Maybe it's redirecting to https://www.youtube.com/watch?v=undefined

yeah I'm on firefox and having this issue too

**Comment by neikeq** [comment]
This was fixed by 0f71353b29bd8467428ded7fbf6b3707aaee73ad in v1.3.1, but for some reason the last version published for Firefox is v1.2.0.

**Comment by doma-itachi** [comment]
Version 1.3.4(1.3.3) for Firefox, including bug fixes for this, has been submitted for review! 86f38822eb6f643fccdcf748722fd2acc7d2f2fe
https://github.com/doma-itachi/Youtube-shorts-block/releases/tag/v1.3.3Fx

**Comment by Rathmox** [comment]
I still haven't closed it but I should have
