### ISSUE TITLE
Why is the Firefox version older than the Chrome version?

### ISSUE THREAD

**Issue by gioxx** [doma-itachi/Youtube-shorts-block#32]
As stated in the subject. @doma-itachi you know that I've been using your extension since you released the first version and I find it essential, but I don't understand why there are several PRs that have been open for a long time but stopped there and - most importantly - why the Firefox version lags behind the Chrome version.
Can I help you in any way?

In the meantime, I can confirm the problem reported in bug #30 and that I now see Shorts also on the main page of the YouTube account:

![immagine](https://github.com/doma-itachi/Youtube-shorts-block/assets/1768601/3321f358-2221-42af-8431-e40e44c31ca8)

Thanks!
Giovanni.

**Comment by doma-itachi** [comment]
I pushed v1.4.0fx (untested). (26cc1a9)

Thanks for the great suggestion! And sorry for your concerns.
Here are my concerns with the Firefox version (& others)
Some of them are off topic, but please bear with me.

1. about "Hide shorts video
Hide shorts video" has been disabled by default for a long time. However, since the Chrome version was often unaware of the configuration (it's a UX issue for extensions that users are unaware of) and often gave low ratings, it was enabled by default in v1.4.0. (#23 )
However, I am wondering if we can take that behavior directly to the Firefox version (few such reviews on AMO)  

In the meantime, I have the following countermeasures in mind
- Display a guide on first startup after installation
- Show somewhere in the Youtube UI that shorts are blocked

2. the name of the "Youtube-shorts block" (#24)
In PR #24, the name was changed to "Youtube Shorts Block".
We have been using the name "Youtube-shorts block" since the beginning of the project, but for foreign language users, do you feel uncomfortable with this hyphenated name? (I live in Japan and am not very fluent in English.)

I am thinking of making the code common between Chrome and Firefox. (by if statements or tools).

**Comment by doma-itachi** [comment]
v1.4.1 has released to AMO :)

**Comment by doma-itachi** [comment]
Hmm...
It appears that mozilla has not yet completed the review process.
![image](https://github.com/doma-itachi/Youtube-shorts-block/assets/94786908/98b6de98-fbfb-43ee-9182-0470ad01e18b)
![image](https://github.com/doma-itachi/Youtube-shorts-block/assets/94786908/488a3fc3-9b68-4d4a-9959-35493315a63d)
